# Generated by Django 3.0.6 on 2020-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=30)),
            ],
        ),
    ]
