# Generated by Django 3.0.6 on 2020-07-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authority',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
