# Generated by Django 3.0.6 on 2020-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200701_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resident_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addresss', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'broker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoSalesman',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resident_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('addresss', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'co_salesman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_registration_number', models.IntegerField(blank=True, null=True)),
                ('representative', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
                ('field2', models.CharField(blank=True, max_length=20, null=True)),
                ('field3', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('scm_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchasing',
            fields=[
                ('customer_purchasing_manager', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_registration_number', models.IntegerField(blank=True, null=True)),
                ('contact_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer_purchasing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSettlement',
            fields=[
                ('customer_settlement_manager', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_registration_number', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer_settlement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productno', models.IntegerField(db_column='ProductNo', primary_key=True, serialize=False)),
                ('main_category', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=20, null=True)),
                ('professionalism_fee_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('potential_fee_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('additional_fee1', models.IntegerField(blank=True, null=True)),
                ('additional_fee2', models.IntegerField(blank=True, null=True)),
                ('additional_fee3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
