# Generated by Django 3.0.6 on 2020-07-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesContent',
            fields=[
                ('sales_num', models.AutoField(primary_key=True, serialize=False)),
                ('product_model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_quantity', models.IntegerField(blank=True, null=True)),
                ('decision_price', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('beginning_purchase', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_conclusion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_content',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SalesContact',
        ),
    ]
