# Generated by Django 3.0.6 on 2020-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_uploadorderfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamsungCode',
            fields=[
                ('samsung_code', models.IntegerField(primary_key=True, serialize=False)),
                ('manager', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'samsung_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scm',
            fields=[
                ('oppty_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('samsung_code', models.IntegerField(blank=True, null=True)),
                ('samsung_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('scm_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('product_model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('beginning_purchase', models.CharField(blank=True, max_length=20, null=True)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('approval_price', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('quote_num', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('delivery_request_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_place', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'scm',
                'managed': False,
            },
        ),
    ]
