# Generated by Django 3.0.6 on 2020-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_samsungcode_scm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('contact_conclusion_date', models.DateTimeField(blank=True, null=True)),
                ('samsung_code', models.IntegerField(blank=True, null=True)),
                ('samsung_sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('point', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('broker', models.CharField(blank=True, max_length=20, null=True)),
                ('scm_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=20, null=True)),
                ('demand', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_place', models.CharField(blank=True, max_length=20, null=True)),
                ('oppty_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('productno', models.CharField(blank=True, max_length=50, null=True)),
                ('buy_place', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_quantity', models.IntegerField(blank=True, null=True)),
                ('decision_unit', models.IntegerField(blank=True, null=True)),
                ('decision_price', models.IntegerField(blank=True, null=True)),
                ('sales_unit', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('delivery_request_date', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proposal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('manager', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'team_manager',
                'managed': False,
            },
        ),
    ]
