# Generated by Django 3.0.6 on 2020-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_proposal_teammanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadOrderFileModel',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='CoSalesman',
        ),
        migrations.DeleteModel(
            name='CustomerPurchasing',
        ),
        migrations.DeleteModel(
            name='CustomerSettlement',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='OrderData',
        ),
        migrations.DeleteModel(
            name='SalesContent',
        ),
        migrations.DeleteModel(
            name='Scm',
        ),
        migrations.DeleteModel(
            name='TeamManager',
        ),
    ]
