# Generated by Django 3.0.6 on 2020-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20200730_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('quote_num', models.IntegerField(primary_key=True, serialize=False)),
                ('oppty_num', models.CharField(max_length=20)),
                ('productno', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=20)),
                ('approval_quantity', models.IntegerField(blank=True, null=True)),
                ('approval_unit', models.IntegerField(blank=True, null=True)),
                ('approval_price', models.IntegerField(blank=True, null=True)),
                ('approval_balance', models.IntegerField(blank=True, null=True)),
                ('total_approval_balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment', models.CharField(blank=True, max_length=20, null=True)),
                ('productno', models.CharField(max_length=50)),
                ('buy_place', models.CharField(blank=True, max_length=20, null=True)),
                ('approval_quantity', models.IntegerField(blank=True, null=True)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('approval_unit', models.IntegerField(blank=True, null=True)),
                ('approval_price', models.IntegerField(blank=True, null=True)),
                ('sales_unit', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('delivery_request_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=20)),
                ('oppty_num', models.CharField(max_length=20)),
                ('quote_num', models.IntegerField()),
            ],
            options={
                'db_table': 'order_data',
                'managed': False,
            },
        ),
    ]
