# Generated by Django 3.0.6 on 2020-08-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_approval_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDepositBalance',
            fields=[
                ('company_registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('deposit_balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_deposit_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('company_registration_number', models.CharField(max_length=20)),
                ('deposit_number', models.IntegerField()),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_amount', models.IntegerField(blank=True, null=True)),
                ('etc', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('company_registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('deposit_number', models.IntegerField()),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_content', models.CharField(blank=True, max_length=100, null=True)),
                ('in_amount', models.IntegerField(blank=True, null=True)),
                ('out_amount', models.IntegerField(blank=True, null=True)),
                ('deposit_balance', models.IntegerField(blank=True, null=True)),
                ('order_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scm',
            fields=[
                ('contact_conclusion_date', models.DateTimeField(blank=True, null=True)),
                ('samsung_code', models.IntegerField(blank=True, null=True)),
                ('samsung_sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('broker', models.CharField(blank=True, max_length=20, null=True)),
                ('scm_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_type', models.CharField(blank=True, max_length=20, null=True)),
                ('demand', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_place', models.CharField(blank=True, max_length=20, null=True)),
                ('oppty_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('productno', models.CharField(max_length=50)),
                ('buy_place', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_quantity', models.IntegerField(blank=True, null=True)),
                ('decision_unit', models.IntegerField(blank=True, null=True)),
                ('decision_price', models.IntegerField(blank=True, null=True)),
                ('sales_unit', models.IntegerField(blank=True, null=True)),
                ('sales_price', models.IntegerField(blank=True, null=True)),
                ('delivery_request_date', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=20)),
                ('recipient_phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_quantity', models.IntegerField(blank=True, null=True)),
                ('quote_num', models.IntegerField(blank=True, null=True)),
                ('approval_unit', models.IntegerField(blank=True, null=True)),
                ('approval_price', models.IntegerField(blank=True, null=True)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_amount', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('billing_date', models.DateTimeField(blank=True, null=True)),
                ('billing_amount', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('quote_num', models.IntegerField()),
                ('oppty_num', models.CharField(max_length=20)),
                ('productno', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=20)),
                ('billing_date', models.DateTimeField(blank=True, null=True)),
                ('billing_amount', models.IntegerField(blank=True, null=True)),
                ('settlement_month', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'settlement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
